### ISSUE TITLE
A version of THEN that collapses duplicate subgoals

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/sml-lcf#2]
This is just a wacky idea I had, and I don't know if it is possible, but it would be so cool if there were a version of the `THEN` tactical that observed duplicate subgoals and presented only a single one, and then shared the derivation in the subderivations somehow.

The reason I'm not sure if it is possible is that I am not talking about the case when a single tactic generates two duplicate subgoals (which would almost never happen). I mean, the case where somewhere deeper in the proof tree, there are duplicate subgoals that are not logically related.

My concern is that something like this might cause "spooky action at a distance", where suddenly the shape of some subtree changes as a result of a change in some unrelated subtree. It may be possible to make it well-behaved, though, if we fix some kind of top-down/left-right ordering on the tree.

Something like this would make work a lot easier, and it might also be good for performance. 

@freebroccolo

**Comment by ghost** [comment]
This is an interesting idea. I'll have to think about it a bit.

There might be a way to think about this in terms of the coverings/neighborhoods I mentioned the other day from the Coquand patterns paper. From that perspective, it might be possible to relax the applicability condition to where the subgoals don't necessarily need to be exactly duplicate (or even equivalent) and it also might provide a story for determining when changes in one part of the tree break things elsewhere (some topology would essentially be making things "well-behaved"). We'd have to develop the tactic theory a bit more to make sense of an approach like this though.

**Comment by jonsterling** [comment]
This is sort of implemented by #10
