### ISSUE TITLE
Why does the LCF signature have goalToString?

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/sml-lcf#5]
I don't understand why I put this in there... Thanks to @jozefg for noticing this.

We should remove it.

**Comment by jozefg** [comment]
It does get used in a couple places in JonPRL (Grepping shows it in `ctt_frontend.sml` and `development.fun`) so a few signatures will have to be adjusted over there. Nothing big though.

**Comment by jonsterling** [comment]
fixed in 51e13d94f0206adbbd5cd1d74bd0882723732bd6
